version: 0.0
os: linux
files:
  - source: /
    destination: /Localizator
permissions:
  - object: /Localizator
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user